start:
	./mvnw clean install
	@echo "Running the application..."
	./mvnw spring-boot:run

run:
	@echo "Running the application..."
	./mvnw spring-boot:run

clean:
	@echo "Cleaning the project..."
	./mvnw clean